# Generated by Django 3.1.4 on 2021-01-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_rear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name='First Name & Middle Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='Family Name'),
        ),
    ]
